### PR TITLE
pass to fallback on try_files failed

### PR DESCRIPTION
**Pull request by kanonji**
## What I did and what I got

```
$ curl http://192.168.13.37/
No input file specified.
```

```
$ cat /var/log/nginx/error.log
2015/08/31 18:12:55 [error] 27657#0: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.13.1, server: app.dev, request: "GET /index.html HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.13.37"
```

## Env

```
$ git show
commit 59653e26e70d9221397d89f811aa006ac9871a24
[snip]
```

Same to https://github.com/FriendsOfCake/vagrant-chef/issues/41 except HEAD rivision.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Wait, so what does this fix?

**Comment by kanonji** [comment]
> Once it is done, browse to `http://192.168.13.37/` in your browser, and you should have some sort of `It works!` page!
> https://github.com/FriendsOfCake/vagrant-chef#installation

I want to see `It works!` page.



This does not have `It works!` but I thinks this must be the page.

## What do I get with this PR

```
$ curl -i http://192.168.13.37/
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 01 Sep 2015 04:46:19 GMT
Content-Type: text/html
Content-Length: 16786
Last-Modified: Mon, 31 Aug 2015 17:38:16 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "55e49108-4192"
X-Served-By: vagrant
Accept-Ranges: bytes

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width"/>
  <style>
/**********************************************
* Ink v1.0.4 - Copyright 2013 ZURB Inc        *
```

This is content of `/etc/nginx/app/index.html` rendered as the screenshot.


### If app/webroot directory exists

```
vagrant@vagrant:/vagrant$ mkdir -p /vagrant/app/webroot
```

In VM.

```
$ curl -i http://192.168.13.37/
HTTP/1.1 403 Forbidden
Server: nginx
Date: Tue, 01 Sep 2015 04:48:39 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive

<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Nginx does not output `/etc/nginx/app/index.html` any more.

```
$ curl -i http://192.168.13.37/foo.html
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 01 Sep 2015 04:49:56 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

For no exist html.

```
$ curl -i http://192.168.13.37/foo.php
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 01 Sep 2015 04:50:01 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
X-Powered-By: PHP/5.5.9-1ubuntu4.11

File not found.
```

For no exist php.


### With app/webroot/index.html, get 200

```
vagrant@vagrant:/vagrant$ touch /vagrant/app/webroot/index.html
```

```
$ curl -i http://192.168.13.37/
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 01 Sep 2015 04:53:48 GMT
Content-Type: text/html
Content-Length: 0
Last-Modified: Tue, 01 Sep 2015 04:53:36 GMT
Connection: keep-alive
ETag: "55e52f50-0"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
X-Served-By: vagrant
Accept-Ranges: bytes
```

**Comment by kanonji** [comment]
I just want to conclude Instration introduction (https://github.com/FriendsOfCake/vagrant-chef#installation) so that I will not get confused like "Wow. I got `No input file specified`. I can not get `It works!`".

* * *

I want to ask about `vagrant init friendsofcake/cakephp-baking`.
With `vagrant init friendsofcake/cakephp-baking` I got a VM that has only one network adapter(NAT).
Git clone way VM has additional network adapter(Host-only) that takes access of `192.168.13.37`.

> This version was created 1 years ago.
> https://atlas.hashicorp.com/friendsofcake/boxes/cakephp-baking

Git clone way uses `bento/ubuntu-14.04` box. But vagrant init way uses `friendsofcake/cakephp-baking` box.
And this box seams bit old.

Is vagrant init way obsoleted currently?

**Comment by josegonzalez** [comment]
Hmmm. @lorenzo I think you built the custom box. Do you think you can rebuild a new one (and document how you did so)?

**Pull request merged**
