### PR TITLE
Use Ubuntu 16.04 instead of 14.04

### PR DESCRIPTION
**Pull request by HarderWork**
Better dev/prod parity against the new Heroku-16 stack.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Does this just work?

**Comment by HarderWork** [comment]
Building the box was successful. So far, I've only created an empty cake project and made it to the Cake welcome page. I'm going to move my project from a precise32-based box, so I can test it for a couple of days to confirm stability.

**Comment by HarderWork** [comment]
Now I've tested the box with Ubuntu 16.04 on a Windows 8 machine, one iMac and one MacBook. Everything works as expected. I use Postgres, Redis and the Heroku gem, and it works fine.

**Comment by josegonzalez** [comment]
Can you verify memcached and mysql, and also update the versions of any packages that are installed?

**Comment by HarderWork** [comment]
MySQL:
Version 5.6.36
Connected to mysql with
mysql -u root -pbananas
mysql -u user -ppassword
Created DB with both users.

Memcached
Version 1.4.25
Connected to instance with
telnet localhost 11211
Basic test:
>set whoami 0 900 5
>Peter
STORED
>get whoami
VALUE whoami 0 5
Peter

Conclusion: It works and versions in Readme.md is correct.

**Pull request merged**
