### PR TITLE
Fixes issue with `vagrant up`

### PR DESCRIPTION
**Pull request by KieranYo**
- Missing chef packages (or rather renamed)
- Changed postgres version from `9.6` to `9.4`

Fixes this issue I submitted https://github.com/FriendsOfCake/vagrant-chef/issues/72

### CODE REVIEW

**Comment by KieranYo** [comment]
Hi @josegonzalez apologies, I closed the PR prematurely. I assume you're just waiting for the Travis CI build to finish first.

**Comment by KieranYo** [comment]
Sorry, this is my first ever PR to an open source project.

**Comment by josegonzalez** [comment]
No worries, I got distracted at work by something. You're all good!

**Comment by josegonzalez** [comment]
Thanks for the pull request!

**Comment by KieranYo** [comment]
Cheers! 👍

**Pull request merged**
